### ISSUE TITLE
Bild Startseite

### ISSUE THREAD

**Issue by mpfeil** [sensebox/sensebox.github.io#1]
lass uns wieder das bild_startseite.jpg nehmen. das sieht besser aus als nur das einzelne Bild der senseBox. vielleicht können wir es etwas kleiner machen.

**Comment by chk1** [comment]
Werde ich ändern

**Comment by mpfeil** [comment]
fixed in dd4d6bd33c09bf9c903f75f9bc34bdf6bc0a8f3e
