### ISSUE TITLE
change team members

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#106]
delete:
Alex
Christoph
Joana
Marc.

add:
Manuela

**Comment by benzmanu** [comment]
Manuela studiert Kommunikationswissenschaft an der Uni Münster. Während ihres Masterstudiums arbeitet sie als studentische Hilfskraft am Institut für Geoinformatik und ist hier für die Betreuung der Social Media Kanäle für die senseBox zuständig. Dabei werden nicht nur Facebook und Twitter von ihr bespielt, sondern auch die Blogbeiträge oder andere Bereiche der Homepage werden auf dem aktuellen Stand gehalten.

**Comment by ubergesundheit** [comment]
done.
