### ISSUE TITLE
please create new page: sensebox.de/feinstaub-workshop

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#108]
Bitte wie das hier aufbauen (termin, ort usw. gleich):

https://ruhrmobil-e.de/veranstaltung/buerger-machen-wissenschaft-feinstaub-sensoren-selber-bauen-in-muenster/

Veranstalter sind aber Ifgi, Warpzone und ruhrmobil e.v. (in dieser Reihenfolge). 
gerne mit logos.

Text:

Beim Feinstaub-Workshop in der Warpzone (URL) kommen Bürger zusammen, die an der Messung von Feinstaub und anderen Umweltphänomenen interessiert sind und die Daten als Open Data veröffentlichen möchten. Besteller des Feinstaub-Sensors von luftdaten.info können vor Ort ihre Sensoren zusammenbauen. Wir werden auch einige Bausätze der senseBox mit der neuen Feinstaub-Erweiterung dabei haben und vor Ort zum Verkauf anbieten. Unser Team betreut bei Bedarf auch beim Aufbau und der Registrierung der Stationen.

(Fotos der Feinstaub-Erweiterung) 

@benzmanu kannst Du dazu dann auch einen Facebook-Event anlegen?

**Comment by felixerdy** [comment]
4402d05e41601a588caeabd654cd3075d57eae3d

**Comment by ubergesundheit** [comment]
done?

**Comment by felixerdy** [comment]
Yes
