### ISSUE TITLE
add Facebook and Twitter buttons / links

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#12]
fb: sensebox.de
twitter: sensebox_de

**Comment by chk1** [comment]
Hab Links in die Footer-Navigation gemacht und bei "News" in die linke Seitenleiste, sieht da aber noch etwas komisch aus

**Comment by robarto** [comment]
ja, wie wäre es auch mit nur den 3 runden logos oben rechts in weiß in die Menüleiste immer ganz rechts... geht das?

**Comment by robarto** [comment]
oder wo kommt der sprach button hin? vielleicht auch da?

**Comment by mpfeil** [comment]
der sprachbutton kommt in die navbar.

die social media buttons sollten schon in den footer.
ich finde das gar nicht so schlecht mit der seitenleiste
