### ISSUE TITLE
Presse /  how to post new articles?

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#13]
Similar solution to News??? Jekyll? 
Articles may have a picture (logo of TV-Station, Screenshot of Newspaper). 

Could look like this: 

1-2 Lines quote from article / news report
Picture / Logo
Link to oroginals source / youtube...

**Comment by chk1** [comment]
It is currently just a single HTML page, but we can make it work dynamically like news or team

**Comment by chk1** [comment]
or simply have a news category "press"

**Comment by chk1** [comment]
You can now add press articles by adding articles to the _press folder, use the same schema as the existing files

**Comment by mpfeil** [comment]
:heart:  it
