### ISSUE TITLE
Add Ardublockly to senseBox Website

### ISSUE THREAD

**Issue by mariopesch** [sensebox/sensebox.github.io#133]
We should add an online Version of Ardublockly to the senseBox website (github.com/sensebox/ardublockly). It would be nice to reach the interface via sensebox.de/blockly.

There need to be some adjustments in the interface, so that the Sketch upload button should not be visible. A button to simple copy the cody to the clipboard would be awesome. 

At the moment it is possible to make some adjustments in the settings of the interface (setup Arduino Board, set Compiler Location) these Options won't be needed in the online version.

**Comment by felixerdy** [comment]
Ardublockly now runs on https://sensebox.de/blockly/ 
The repo is https://github.com/sensebox/blockly
