### ISSUE TITLE
Main Page Sensor List

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#14]
What about the Squares in front of the Phenomena??? 
Waren das die Icons, die Eric gemacht hat???

Sensor Names and links:

Temperatur, Einheit: Grad C, Sensor HDC1008, Link: http://www.ti.com/lit/ds/symlink/hdc1008.pdf

Beleuchtungsstärle, Einheit: Lux (lx), Sensor: TSL45315 Link: http://ams.com/eng/Products/Sensor-Driven-Lighting/SDL-Ambient-Light-Sensors/TSL45315

realtive Luftfeucht, Einheit: % Sensor/ Link wie bei temp

UV(A)-Intensität, Einheit: μW/cm² (UV-Index), Sensor: VEML6070 Link: http://www.vishay.com/docs/84277/veml6070.pdf

Luftdruck, Einheit: hPa, Sensor: BMP280, Link: https://www.bosch-sensortec.com/en/homepage/products_3/environmental_sensors_1/bmp280/bmp280

weitere Phänomene:
Lautstärke
Distanz (Infrarot, Ultra Schall)
und vieles mehr (LINK zu Products)

**Comment by chk1** [comment]
Correct sensor descriptions added
Squares also added
