### ISSUE TITLE
Wrong URL when changing Blog from English back to German

### ISSUE THREAD

**Issue by baender** [sensebox/sensebox.github.io#140]
Having the blog open in English the page uses this URL:
https://sensebox.de/en/blog

Changing the language back to German, the site tries to access this non-existing URL:
https://sensebox.de/de/blog

The actual URL for the blog in German is:
https://sensebox.de/blog

If you want to stay consistent, you should change the German blog URL to:
https://sensebox.de/de/blog
as this is working for all the other pages (Produkte, openSenseMap, etc...)

**Comment by felixerdy** [comment]
@baender Tank you!

**Comment by ubergesundheit** [comment]
This breaks opening the blog by just typing the old url in the address bar sensebox.de/blog

**Comment by felixerdy** [comment]
@ubergesundheit should work now d6759bae10a6810f3d64a990f0dceb942da30f3d
