### ISSUE TITLE
url-Fehler 404

### ISSUE THREAD

**Issue by pejonp** [sensebox/sensebox.github.io#141]
beim Sprung von der Seite https://opensensemap.org/info ..
Über openSenseMap

Die openSenseMap ist eine Plattform für offene Sensordaten, an der jeder teilnehmen kann.
Das Projekt entstand 2015 im Rahmen von GI@School am Institut für Geoinformatik in Münster, wo es zusammen mit der  **senseBox**
 eingesetzt wird, um Schülern und interessierten Bürgern eine Plattform zu bieten, um ihre Messdaten zu sammeln und zu veröffentlichen.

**senseBox** ->URL  https://www.sensebox.de/de/products/ kommt ein Fehler

**Comment by mpfeil** [comment]
Links sollten nun alle funktionieren.
