### ISSUE TITLE
Create new Page: senseBox:edu

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#142]
add more information about senseBox:edu and the Klassenkiste, it's STEM (MINT) approach. @Bernd90 can you write it?
add links to books and to distinct examplary projects
add a Map with schools/institutions that already have a Klassenkiste, maybe give some information about how it's being used and by whom.  Get overview from @bgunt @mariopesch who received 10 boxes in the first phase of the project.  Schülerlabore and FabLabs...

From a funding through Stadt Münster we gave Klassenkisten to the following schools:
- Ratsgymnasium Münster
- Wilhelm-Hittorf-Gymnasium Münster
- Gymnasium Wolbeck
- Kardinal-van-Galen Gymnasium Münster
- Marienschule Münster

from the CeBIT Innovation Award:
- Annette-Gymnasium Münster
- MakerLab Murnau
- Eigenbaukombinat, Halle (Saale)
- FabLab Bayreuth
- FabLab Dortmund
- Deutsches Museum Bonn
- Hero Society Leipzig

add a possibility so schools can add themselves to the map and receive news in the future (new projects in books)

**Comment by noerw** [comment]
For the map you could use a subset of the [geojson file used in 'schulen in nrw'](https://github.com/CodeforRuhrgebiet/schulen-in-nrw/blob/gh-pages/js/schools.geojson).

**Comment by robarto** [comment]
Liste of schools and other entities who received a senseBox Klassenkiste https://docs.google.com/spreadsheets/d/19GhvLtmruWIA3oV-Nb8KIU3__rPArIEW6eEzIlkkqms/edit#gid=0
