### ISSUE TITLE
bitte meinen Text und Foto ändern

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#162]
![thomas_bartoschek_portrait](https://user-images.githubusercontent.com/3996475/36366338-f54aa64a-154d-11e8-9aa5-a1e43724954a.jpg)

Thomas ist Wissenschaftlicher Mitarbeiter (Post-Doc) am Institut für Geoinformatik der Westfälischen Wilhelms-Universität Münster. Er ist Gründer und Leiter des Forschungs- und Schülerlabors GI@School und Leiter des senseBox Projektes. Er forscht in den Bereichen „Lernen mit Geotechnologien“, Human-Computer-Interaction und Citizen Science und entwickelt Produkte für Bildung und Kommunikation seiner Wissenschaft. 

Thomas is a Postdoctoral Researcher at the Institute for Geoinformatics at the University of Muenster. He is founder and leader of the GI@School Lab and of senseBox. His research focus is on learning with geotechnologies, human computer interaction and citizen science. He develops products for education and communication of his science.

**Comment by ubergesundheit** [comment]
fixed by @buchwaldchassee in #165
