### ISSUE TITLE
Björn Bio

### ISSUE THREAD

**Issue by bgunt** [sensebox/sensebox.github.io#17]
Björn ist Lehramtsstudent an der Universität Münster und arbeitet als studentische Hilfskraft bei GI@School. Er hat für seine Bachelorarbeit den Prototypen der senseBox:WaterQuality entwickelt. Björn unterstützt das senseBox Team hauptsächlich bei der Durchführung von Workshops und bei der Entwicklung neuer Unterrichtskonzepte.

**Comment by mpfeil** [comment]
@bgunt ist deine senseBox:WaterQuality auf github?
