### ISSUE TITLE
Bio von Alex

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#18]
missing

und die FOtos auch ;)

**Comment by mpfeil** [comment]
kontrolliert bitte alle die senseBox Schreibweise

**Comment by chk1** [comment]
Sergey und @janwirwahn sollen bitte auch nochmal ihre Biographien durchlesen, habe die Texte einfach von der alten Homepage kopiert

**Comment by robarto** [comment]
wie läuft das hier mit den Fotos? kann ich die auch irgendwo verlinken in den markdowns vom team?

**Comment by chk1** [comment]
Ja das geht. Wenn du eine Team Datei öffnest, dann siehst du so eine Zeile ganz oben:
`image: /images/team/raute.png`

Da einfach die Adresse zu deinem Bild reinschreiben, entweder so wie jetzt (relativer Pfad) oder kompletter Pfad auf einen anderen Webserver

**Comment by mpfeil** [comment]
Sergey hat den ftp eingerichtet.
Ich lade die Fotos so gegen 22 Uhr hoch denke ich

**Comment by robarto** [comment]
alles klar. habs dann auch gesehen ;)

**Comment by robarto** [comment]
Bio von Joana:
Joana hat den Bachelor of Science in Geoinformatik an der Uni Münster studiert. Als Master Studentin am Institut für Geoinformatik wird sie weiterhin die Arbeitsgruppe Gi@school unterstützen. Zusammen mit dem senseBox Team stellt sie interessierten Bürgern die senseBox:home und die openSenseMap vor. Das Programmieren und Aufbauen der senseBox:edu legt sie Schülern verschiedener Altersklassen nahe. In ihrer Bachelorarbeit werden Methoden zum Bereinigen von Daten gemessen mit der senseBox erprobt und herausgestellt, zusätzlich werden Vorteile von low-cost Sensoren vorgestellt.

**Comment by robarto** [comment]
Eng: Aleksandr Shirokov is a Master Student at the Institute for Geoinformatics (ifgi) working as a student assistant in the Spatial Intelligence Lab at WWU. He holds a bachelor degree in Information Technology in GIS and is currently actively participate in various projects at ifgi. As part of the senseBox team Aleksandr is mainly responsible for the development and maintenance of openSenseMap. 

De:  Aleksandr Shirokov ist Geoinformatik-Student und arbeitet als studentische Hilfskraft beim Spatial Intelligence Lab an der WWU. Er hat einen Bachelor of Science in Information Technology in GIS und  arbeitet jetzt neben seinem Studium an vielen Projekten am ifgi mit. Im senseBox-Tea ist er für die Weiterentwicklung und die Pflege der openSenseMap zuständig.

**Comment by robarto** [comment]
Mario En:
Mario studies chemistry and geography at the University of Muenster and works as a student assistant at the GI@School Lab. In his bachelor thesis Mario developed a prototype for measuring Air Quality with the senseBox. Mario supports the team with workshops in schools and is looking for new use cases for the senseBox.

**Comment by robarto** [comment]
wo lege ich das Foto von Alex ab? Oder kann das einer von euch machen? Ich poste jetzt hier auch die restlichen Team-Texte auf Englisch. Hier sind ja auch andere Team-Texte gedroppt worden...

**Comment by robarto** [comment]
Thomas is a Research Associate at the Institute for Geoinformatics at the University of Muenster. He is founder and leader of the GI@School Lab and of senseBox. His research focus is on learning with geotechnologies, human computer interaction and citizen science. He develops products for education and communication of his science.

Jan is a student assistant at the GI@School Lab. He is the developer of the weatherSenseBox, one of the first use cases for the senseBox in education. He is teaching and instructing students and teachers in the use of senseBox at the Institute for Geoinformatics an in secondary schools. His interests are in the hardware business, in particular Arduino microcontrollers and all kinds of sensors.

**Comment by chk1** [comment]
Schick mir mal das Foto per Email, dann füg ich das später mit ein

**Comment by robarto** [comment]
ist in ner gesonderten mail raus

2015-11-30 22:58 GMT+01:00 Chr. Ki. <notifications@github.com>:

> Schick mir mal das Foto per Email, dann füg ich das später mit ein
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sensebox/sensebox.github.io/issues/18#issuecomment-160774562>
> .
>



-- 
--

Thomas Bartoschek
ifgi - Institute for Geoinformatics
University of Münster
Heisenbergstr. 2
48149 Münster, Germany

Phone:  +49 (0)251 83 30011
Mobile: +49 (0)173 511 6094
Fax:    +49 (0)251 83 39763

Email: bartoschek@uni-muenster.de
http://ifgi.uni-muenster.de/
http://www.gi-at-school.de/
http://vespucci.org/

**Comment by robarto** [comment]
kannst du das foto noch einpflegen?

**Comment by chk1** [comment]
jo ist drin
