### ISSUE TITLE
Dead Link on sensebox.de/de/awards

### ISSUE THREAD

**Issue by synolus-david** [sensebox/sensebox.github.io#196]
The Link to "Photonik Forschung Deutschland" doesn't work anymore.

**Comment by mpfeil** [comment]
@buchwaldchassee kannst du mal schauen, ob du den Artikel auf den neuen Seiten finden kannst:
https://www.photonikforschung.de/make-light.html oder
https://www.photonikforschung.de/campus.html

**Comment by umut0** [comment]
Merged in Master, changed 3 links
