### ISSUE TITLE
Umstrukturierung Startseite

### ISSUE THREAD

**Issue by mpfeil** [sensebox/sensebox.github.io#20]
Ich habe unterschiedlichen Leuten mal die Startseite unserer neuen Homepage gezeigt und alle waren etwas überfordert mit den 6 Sensorpunkten.

Was haltet ihr davon, wenn wir nur das Startbild hinpacken plus einen passenden Satz. Das ganze wird immer 100% einnehmen. Siehe letzter Kommentar #2 

Und als Satz oder Headline können wir doch `A good way to make sense is to make stuff`nehmen.

Was meint ihr?

**Comment by mariopesch** [comment]
:+1:

**Comment by robarto** [comment]
Alles Klar. Aber Lasst uns das bitte ein mal so wie es ist fertig machen.
Die Seite steht doch schon fast... Macht doch mal diese Grafiken vor die 6
Punkte auf der Startseite... Danach können wir gerne über änderungen
nachdenken.
Am 17.10.2015 10:12 schrieb "Mario Pesch" <notifications@github.com>:
