### ISSUE TITLE
Add more Information to "Upcoming Events"

### ISSUE THREAD

**Issue by synolus-david** [sensebox/sensebox.github.io#203]
Is it possible to add some more information to "upcoming events"? There are many teachers, open science activists etc. asking for workshops in their area. Maybe we can put an additional line saying: "for teachers, no fee, sign-up necessary" or "for children, 3h, 200 Euro, sign-up necessary".

**Comment by mpfeil** [comment]
@synolus-david maybe we should add these information to our `product` page or add a new page `events`. Right now the `upcoming events` are just visible as boxes on the website.

Or do you want to add these information to these boxes?

**Comment by synolus-david** [comment]
@mpfeil better no new pages...let's keep it like that for the Moment!
