### ISSUE TITLE
SenseBox or senseBox

### ISSUE THREAD

**Issue by janwirwahn** [sensebox/sensebox.github.io#21]
Hey guys, I don't know about you, but the small case "senseBox" is not working for me at all! We should revive "SenseBox" and "OpenSenseMap". All publications and thesis are using upper case too. What do you think?

**Comment by robarto** [comment]
Ich hoffe das ist nicht dein ernst...

On Mon, Oct 19, 2015 at 7:11 PM, Jan Wirwahn <notifications@github.com>
wrote:

> Hey guys, I don't know about you, but the small case "senseBox" is not
> working for me at all! We should revive "SenseBox" and "OpenSenseMap". All
> publications and thesis are using upper case too. What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sensebox/sensebox.github.io/issues/21>.
>



-- 
--

Thomas Bartoschek
ifgi - Institute for Geoinformatics
University of Münster
Heisenbergstr. 2
48149 Münster, Germany

Phone:  +49 (0)251 83 30011
Mobile: +49 (0)173 511 6094
Fax:    +49 (0)251 83 39763

Email: bartoschek@uni-muenster.de
http://ifgi.uni-muenster.de/
http://www.gi-at-school.de/
http://vespucci.org/

**Comment by mpfeil** [comment]
:unamused: :gun:

**Comment by janwirwahn** [comment]
Was denn? :) da haben wir uns doch schon drüber unterhalten

**Comment by robarto** [comment]
okay, nach einer 5000€ teuren designer-aktion, und fast einem Jahr Prozess die Webseite in ein neues design zu überführen. Und nach vielen Einsätzen des neuen Logos mit neuer Schreibweise (Facebook, Twitter, Bedruckung Boxen, Konferenzpräsentationen) sollten wir es dringend dabei belassen, anstatt eine neue Diskussion zu eröffnen, die den fast abgeschlossenen Prozess zu einer vernünftigen Webseite zu führen ins Stocken bringen würde.
