### ISSUE TITLE
Link to senseBox Forum

### ISSUE THREAD

**Issue by synolus-david** [sensebox/sensebox.github.io#211]
Please put a link to https://forum.sensebox.de/ in the header.

**Comment by synolus-david** [comment]
@umut0 kann das auch?

**Comment by synolus-david** [comment]
Status?

**Comment by mpfeil** [comment]
ist noch nicht drin. vielleicht kann @umut0 das übernehmen und irgendwo einbauen

**Comment by umut0** [comment]
done
