### ISSUE TITLE
Texte senseBox 

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#22]
2. Zeile: senseBox:home zuerst nennen. Machen wir sonst auch immer. 
2. Anbschnitt: hinter WLAN "oder LAN-Anschluss" ergänzen. 

Unter die beiden Box-Präsentationen explizit die Lizenzen nennen, wieder im rechten Block-Teil. Genau wie im Hintergrund mit den Links zu den Lizenzen:

Die Zusammenstellung der senseBox-Komponenten ist unter der CERN Open Hardware Lizenz 1.2 offen. Der Source Code der senseBox:home ist Open Source unter der LGPL 3.0 Lizenz verfügbar. Die Anleitungen (hier Link zu Docs setzen) sind Open Educational Resources (OER) unter der Creative Commons Lizenz CC BY SA 4.0.

**Comment by chk1** [comment]
Hab die von dir erwähnten Dinge korrigiert und ergänzt, über die Features-Listen müsstest du nochmal drübergucken. Die Fotos auch noch durch passendere tauschen.

Ich hab davon abgesehen, das große Foto wie in der Vorlage drunterzusetzen. Meiner Meinung nach passt das nicht gut, würde den ganzen Bildschirm unnötig füllen und sieht auf großen Auflösungen nicht gut aus.

**Comment by robarto** [comment]
Danke
