### ISSUE TITLE
senseBox Schreibweise auf https://sensebox.de/de/blockly

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#222]
in den button-links zu blockls steht "SenseBox"

Ich würde noch dafür appelieren, das noch deutlicher zu beschreiben:
habe das gefühl, dass wir nirgendwo v1/v2 oder gen1/gen2 schreiben... darum wäre das mein vorschlag: 

z.B. 
Blockly für senseBox mit Arduino/Genuino UNO 
Blockly für senseBox mit senseBox MCU (ab Mai 2018)  

was meint ihr?

**Comment by mariopesch** [comment]
vielleicht sollten wir unabhängig davon auch noch die Landingpage direkt in Blockly integrieren? Bzw. das die nur dann angezeigt wird, wenn der Zugriff nicht über die Blockly Seite auf sensebox.de erfolgt? @jasperbuss

**Comment by jasperbuss** [comment]
Das wäre ja genau das, was ich auch schon gemacht habe

Mario Pesch <notifications@github.com> schrieb am Mo. 11. Juni 2018 um
09:17:

**Comment by mpfeil** [comment]
@umut0 branch heißt `blockly-caption`
