### ISSUE TITLE
https://sensebox.de/de/books

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#223]
auch hier die Schreibweise von senseBox checken.

auch hier die offene Diskussion rund um v1 v2... 

Durch die ziemliche Umgestaltung der Seite kann man hier nicht mehr PDFs der Books generieren. 
Außerdem war da auf der alten Seite doch noch ein kurzer Text, auch darüber dass das OER ist und welche LIzenz, oder?

**Comment by mpfeil** [comment]
@umut0 kannst du das hier auch übernehmen?

ich würde fast sagen, das man v1 und v2 in den Buttons gar nicht brauch. man wählt die Version ja schon durch den klick auf das Bild.

@robarto die Lizenz steht noch drin. Oder fehlt da was?

> Hier finden Sie die gesamte Dokumentation rund um die senseBox. Alle hier befindlichen Anleitungen sind Open Educational Resources (OER) unter der Creative Commons Lizenz CC BY SA 4.0. Bestehende Texte können so nach und nach von der kreativen Gemeinschaft weiterentwickelt, sowie durch neue Experimente oder Projekte erweitert werden. 

Das PDF müssen wir noch generieren. @bkari02 kannst du dir das mal anschauen, wie das in der ersten Version der Books gemacht wurde?

**Comment by umut0** [comment]
yo mach ich!
den text hab ich grad wieder dazu geschrieben, stand vorher nicht da.

**Comment by mpfeil** [comment]
Seite und Schreibweise wurde aktualisiert.

**Comment by bkari02** [comment]
PDF schau ich mir nächste Woche mal an
