### ISSUE TITLE
Docs/Fotos

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#27]
Hier sollte unter Fotos statt einer Liste, eine Gallery sein, die ALLE Fotos aus den News beinhaltet.

**Comment by chk1** [comment]
https://blog.omgmog.net/post/extract-the-first-image-from-a-post-in-jekyll/

**Comment by chk1** [comment]
Alle Fotos, die mit `<img src="http://sensebox.org/..." />` von der Adresse sensebox.org kommen werden nun unter Docs - Fotos gelistet 
5af3a9531eca474278d5fd2605e13ec31e0581f2

**Comment by chk1** [comment]
Neues Problem, Idee für die Zukunft: 

Kleine extra-Seite/Gallerie für Fotos mit Pagination (nur x Fotos pro Seite anzeigen wie bei Newsartikeln), wenn die Liste unter Docs zu lang wird, da dort Pagination nicht wirklich... machbar ist
