### ISSUE TITLE
Type-Os / Ergänzungen

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#34]
Startseite:
senseBox:edu Text:
"Für Schulen und Nachwuchsforscher gibt es die..."

http://www.sensebox.de/products/
senseBox:edu Text:  
Mit der senseBox:edu bieten wir Schülern und Nachwuchsforschern ab der 7. Klasse die Möglichkeit, das Programmieren auf eine spielerische Art und Weise zu erlernen, sich als Citizen Scientist zu betätigen und die Welt der Geoinformatik kennen zu lernen. 

http://www.sensebox.de/osem/
Letzter Satz, o in openSenseMap fehlt.
OSeM URL in neuem Tab öffnen.
URL auch hinter Screenshot legen.

http://www.sensebox.de/background/
Über uns teil ist nicht gut, im zweiten Satz fehlt ein Verb... Hier ein neuer, korrigierter Absatz:

Unser Team des Schüler- und Forschugnslabors GI@School (link) am Institut für Geoinformatik (link) sammelt seit mehreren Jahren praktische Erfahrung in Workshops mit Schülern und Lehrern. Dabei hat sich herausgestellt, dass die Datenerhebung mit selbstgebauten Sensorstationen einen besonders zugänglichen Weg bei der Arbeit mit Geoinformation und Umweltdaten bietet. Ganz nebenbei werden Kompetenzen in der Programmierung auf eine sehr anschauliche Art und Weise vermittelt. Diese Erfahrung führte zur Entwicklung der senseBox:edu basierend auf Arduino Mikrokontrollern, Sensoren und Zubehör zur Gruppenarbeit im Klassen-/Kurskontext. Die senseBox:home ergänzt diesen Ansatz und komplettiert das Citizen Science Toolkit. 

Unter OPEN SCIENCE fehlt ein Punkt hinter der OSeM Lizenz, ebenso nach der OER Lizenz. 

SERGEY: Außerdem zusammen
JAN: "im MexLab" ersetzen durch "am Insitut für Geoinformatik" 
MATTHIAS: OpenSenseMap konsistent schreiben, URL ist falsch
JOANA: GI@School richtig schreiben

**Comment by mpfeil** [comment]
sollte alles drin sein.

ich bin mir nicht sicher, wie wir mit der Kleinschreibung bei SenseBoxen umgehen sollen. Kommt öfters im Text vor.

Und wir sollten schauen, was wir alles hervorheben und als Link versehen wollen.
