### ISSUE TITLE
sensebox.uni-muenster.de

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#35]
zeigt alte seite. Wie machen wir die Weiterleitung?
wo liegt die neue Seite eigentlich?

Es sollte eigentlich so sein, dass sie auf dem Uni-Server liegt und www.sensebox.de sich da die Inhalte herholt..

**Comment by mpfeil** [comment]
Also die neue Seite wird über GitHub-Pages gehostet. Das Repository ist die Seite.

www.sensebox.de zeigt auf sensebox.github.io und da liegt die Seite.

**Comment by robarto** [comment]
ach wunderbar. auch gut. es wäre gut, wenn wir auch sensebox.uni-muenster.de darauf zeigen lassen könnten. @chk1 kannst du das irgendwie organisieren?

**Comment by mpfeil** [comment]
@chk1 ich bin mir gerade nicht sicher, aber können wir nicht einfach die URL auch in CNAME packen?

**Comment by chk1** [comment]
Bin mir nicht sicher ob die Uni CNAMEs auf ihre Subdomains erlaubt und einstellt, eine einfache Weiterleitung auf dem Server, wo die Domain gerade hinzeigt, wäre aber möglich.

**Comment by mariopesch** [comment]
mir ist gerade aufgefallen, dass sensebox.de (ohne www davor) noch eine testseite von 1blu anzeigt. können wir das auch noch irgendwie umstellen?

**Comment by chk1** [comment]
Ja da sind wir schon dran

**Comment by mpfeil** [comment]
gibt es hier zu dem Eintrag mit WWW davor schon was neues? scheint noch nicht zu funktionieren.

**Comment by robarto** [comment]
habe hierzu ein Ticket bei webteam erstellt.

**Comment by robarto** [comment]
done!
