### ISSUE TITLE
wiki in den docs verlinken

### ISSUE THREAD

**Issue by mariopesch** [sensebox/sensebox.github.io#36]
Können wir das oer wiki noch unter den docs verlinken? Aktuell ist das oer-repo verlinkt.

**Comment by robarto** [comment]
Ja, aber zieh das noch erst von deinem Account in den sensebox oer Ordner.
Am 20.11.2015 12:13 nachm. schrieb "Mario Pesch" <notifications@github.com>:

**Comment by mariopesch** [comment]
das ist schon längst passiert, ist jetzt alles unter: https://github.com/sensebox/OER/wiki

**Comment by mpfeil** [comment]
schauen wir uns an und übernehmen es dann

**Comment by robarto** [comment]
Der Wiki ist nun korrekt.
kann also wie folgt verlinkt werden und der issue geschlossen werden.

Im Wiki (URL: https://github.com/sensebox/OER/wiki) auf unserem Github Repository finden Sie stets aktuelle Anleitungen zur senseBox:home, senseBox:edu und openSenseMap. (letztere ohne URL).
