### ISSUE TITLE
Links sind kaputt

### ISSUE THREAD

**Issue by chk1** [sensebox/sensebox.github.io#38]
Die Links auf der Hauptseite (und andere) verweisen auf `http://www.sensebox.de/{{ site.url }}` u.ä. statt zur korrekten Adresse

**Comment by mpfeil** [comment]
wir müssen die liquid Ausdrücke in den Sprachdateien ersetzen

**Comment by robarto** [comment]
was kann ich machen? habe ich was falsch gemacht?
kriegen wir das vor abends hin? es hat sich schon jemande gemeldet ;)

**Comment by mpfeil** [comment]
Es hat sich schon jemand gemeldet?

Ne ich habe es falsch gemacht. Wir müssten in den Sprachdateien die Links, die  {{ site.url }} und so weiter durch www.sensebox.de/de/products ersetzen. (oder den entsprechenden Link). Ich habe gestern Abend schon angefangen, dass für die deutsche Übersetzung zu machen.

Heute werde ich es wohl nicht schaffen. Wir gehen auf den Weichnachtsmarkt :christmas_tree: :santa:

**Comment by robarto** [comment]
ich kann es machen. denke dass ich es hinkriege

**Comment by robarto** [comment]
hast du schon was  commited? weil im de.yml schon im ersten sbastaz der erste link immer noch site.url ist...

**Comment by mpfeil** [comment]
Ne habe noch nichts commitet, weil ich noch versucht habe nach einer Lösung zu suchen. Die bekommen wir aber so nciht hin.

Kannst gerne die Dateien bearbeiten. Merge das dann bei mir.

**Comment by robarto** [comment]
Ich denke dann arbeite ich einfach online in der master-branch und mache
das schnell fertig ;)

2015-12-03 10:44 GMT+01:00 Matthias Pfeil <notifications@github.com>:

> Ne habe noch nichts commitet, weil ich noch versucht habe nach einer
> Lösung zu suchen. Die bekommen wir aber so nciht hin.
>
> Kannst gerne die Dateien bearbeiten. Merge das dann bei mir.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sensebox/sensebox.github.io/issues/38#issuecomment-161569640>
> .
>



-- 
--

Thomas Bartoschek
ifgi - Institute for Geoinformatics
University of Münster
Heisenbergstr. 2
48149 Münster, Germany

Phone:  +49 (0)251 83 30011
Mobile: +49 (0)173 511 6094
Fax:    +49 (0)251 83 39763

Email: bartoschek@uni-muenster.de
http://ifgi.uni-muenster.de/
http://www.gi-at-school.de/
http://vespucci.org/

**Comment by robarto** [comment]
done
