### ISSUE TITLE
Wiki Short Link

### ISSUE THREAD

**Issue by mariopesch** [sensebox/sensebox.github.io#39]
Für unsere "How to get started" Broschüre wäre es cool wenn wir einen fix link für das wiki bekommen z.B. www.sensebox.de/wiki sodass von dort automatisch zum Github Wiki verlinkt wird.

**Comment by chk1** [comment]
https://github.com/sensebox/sensebox.github.io/commit/7cd47fd756b01c3bcb4b87baff0f90a30af2cf5c
