### ISSUE TITLE
Bilder in Blogeinträgen

### ISSUE THREAD

**Issue by mpfeil** [sensebox/sensebox.github.io#4]
Bilder hinzufügen -> Struktur?

**Comment by chk1** [comment]
Ich würde Vorschlagen Bilder in den Ordner `images/news/` zu tun, dort einen Unterordner pro News oder Datum, also z.B. `images/news/2015-10-01/ein-bild.jpg`. Weiß nicht ob die Generierung von thumbnails einfach möglich ist, dann sollte man noch kleine Fassungen (bis max. ~300x300) dort ebenfalls mit hochladen: `images/news/2015-10-01/ein-bild-thumbnail.jpg`

Verlinken müsste man über HTML oder eben Markdown

**Comment by mpfeil** [comment]
Die Idee war, dass über einen Dropbox-Ordner zu regeln.
Der Upload von Fotos ist hier ja nicht so leicht. Müsste über den Desktop Client von Github laufen. Ich weiß nicht wie gut die Autoren damit zurecht kommen.

Das Problem bei Dropbox ist, ich habe noch nicht rausgefunden, wie ich auf den Ordner über eine statische Url komme. Das ist irgendwie etwas kompliziert.

@chk1 hast du das schon einmal gemacht oder Erfahrung?

**Comment by robarto** [comment]
https://www.dropbox.com/sh/o8jamtsud5ynuoj/AAA_-0r5bC2L-t4yeGLwAUJqa?dl=0

check mal ob das statisch ist

**Comment by mpfeil** [comment]
der ordner ist leer. sollte da was drin sein?

**Comment by robarto** [comment]
Richtig. Tu mal was rein und Check. Ist doch ein statischer link..
Am 15.10.2015 12:36 schrieb "Matthias Pfeil" <notifications@github.com>:

**Comment by mpfeil** [comment]
ich kann da nicht wirklich was reinpacken.

habe es gestern ja auch ausprobiert und sobald ich einen Ordner anlege und da was reinpacke, muss ich jedes mal "Copy Shareable Link" anklicken, damit ich einen Link zu dem Bild habe. Und da ändert sich die komplette Url.

**Comment by robarto** [comment]
hmpf

**Comment by mpfeil** [comment]
habe nur irgendwo gelesen, dass es bei dropbox irgendwo eine url gibt die so aussieht: `dropbox.com/u/id`

habe die aber nirgends gefunden. darüber kann man anscheinend auf seine folder und files zugreifen

**Comment by chk1** [comment]
Ich glaube Fotos müssen in den "Public" Ordner, da hat man die Möglichkeit den "Public Link" zu kopieren: https://dl.dropboxusercontent.com/u/12862952/logo.png

Dropbox hat allerdings auch ein Limit was Traffic und Anzahl der Downloads angeht, siehe https://www.dropbox.com/help/4204

**Comment by mpfeil** [comment]
Danach habe ich die ganze Zeit gesucht und den Button "Public Link" nirgends gefunden.
Ich schaue nochmals nach. Danke

**Comment by mpfeil** [comment]
@chk1 @robarto den Public Folder kann man nicht für andere freigeben. Andere können den Public Folder nur betrachten und nichts hochladen.

Haben wir eine andere Idee? Was sein könnte, wenn wir Dropbox for Business nutzen, könnte es funktionieren.

**Comment by robarto** [comment]
Dann lieber andere Lösung.
Am besten was wo man ohne über ftp o.ä. In einen Ordner aus github saß
hochladen könnte. Dann den link im markdown setzen. Gibt's da nix?
Am 17.10.2015 09:50 schrieb "Matthias Pfeil" <notifications@github.com>:

**Comment by mpfeil** [comment]
Ich habe jetzt nochmal instagram, flickr und 500px gecheckt. Leider funktioniert es nirgendwo einen Ordner anzulegen und den Dateinahmen anzupassen, sodass wir immer einen statischen Aufbau einer Url haben. `anbieter/ordner/x.jpg`

Ich habe nichts gefunden. Falls jemand was weiß bitte melden.

Ansonsten müssen wir es über einen FTP machen, den Sergey einrichtet oder ihr müsst die Blogposts über das Desktop Tool von Github schreiben und die Fotos direkt mit in den Blogpost Folder packen und über Markdown referenzieren.

**Comment by robarto** [comment]
ok, mittlerweile denke ich, dass es hier auch ne doppelung zu Facebook gäbe... 
Wie wäre es hier Facebook Feeds zu zeigen? Allerdings auch mit Fotoalben, wenn welche eingebunden werden. gibt es da ein tool?? 
Wordpress hat z.B. viele Plugins, wo du neben dem Feed auch gut gezielt alben einer Page einbinden kannst. siehe unser gistory blog...

dann würde ich gerne irgendwo noch nur ne Liste mit events haben, wo wir waren, weil die so geil fett wäre...

**Comment by mpfeil** [comment]
für die liste mit events ein neues issue

kenne kein tool dafür.
ich würde vorschlagen wir entscheiden uns zwischen:
* ftp
* github fotos direkt hier im repo

ich tendiere zum ersten

**Comment by mpfeil** [comment]
Sergey richtet einen FTP ein, wo die Bilder abgelegt werden können.
Sobald das fertig ist, baue ich es in die Blogposts ein

**Comment by robarto** [comment]
sehr gut.
dann auf dem FTP ordner mit Artikelnamen anelgen und Fotos rein?

2015-10-20 8:35 GMT+02:00 Matthias Pfeil <notifications@github.com>:

> Sergey richtet einen FTP ein, wo die Bilder abgelegt werden können.
> Sobald das fertig ist, baue ich es in die Blogposts ein
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sensebox/sensebox.github.io/issues/4#issuecomment-149448742>
> .
>



-- 
--

Thomas Bartoschek
ifgi - Institute for Geoinformatics
University of Münster
Heisenbergstr. 2
48149 Münster, Germany

Phone:  +49 (0)251 83 30011
Mobile: +49 (0)173 511 6094
Fax:    +49 (0)251 83 39763

Email: bartoschek@uni-muenster.de
http://ifgi.uni-muenster.de/
http://www.gi-at-school.de/
http://vespucci.org/

**Comment by mpfeil** [comment]
:+1: so wird es laufen
können dann dort auch die Pressebilder ablegen

**Comment by robarto** [comment]
läufts eigentlich schon?

**Comment by chk1** [comment]
der FTP geht, ist aber zur Zeit nur mein Testbild hochgeladen

**Comment by robarto** [comment]
up ;)
