### ISSUE TITLE
Tippfehler unter "Hintergrund"

### ISSUE THREAD

**Issue by bgunt** [sensebox/sensebox.github.io#40]
Unter Hintergrund/Über Uns steht als sechstes Wort Forschugnslabors.

**Comment by mpfeil** [comment]
Du kannst den Tippfehler hier korrigieren:
https://github.com/sensebox/sensebox.github.io/blob/master/_data/translations/de.yml#L98

**Comment by robarto** [comment]
@bgunt  und?
