### ISSUE TITLE
Speichern einer neu angelegten, manuell konfigurierten SenseBox nicht immer möglich

### ISSUE THREAD

**Issue by zven** [sensebox/sensebox.github.io#41]
Falls für die manuell konfigurierte SenseBox bei einem Sensor nicht jedes Feld ausgefüllt ist, lässt sich die Box nicht speichern (in meinem Beispiel habe ich ein Unit-Feld nicht ausgefüllt). Dass alle Felder ausgefüllt werden müssen, wird nirgends erwähnt oder abgefangen.

**Comment by chk1** [comment]
Danke für die Fehlermeldung und Fehlersuche, ich habe dazu ein Issue im OpenSenseMap Repository angelegt: https://github.com/sensebox/OpenSenseMap/issues/72
