### ISSUE TITLE
New Tab: Grants and Awards

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#43]
I would like to add a new tab and tell the senseBox story from the point of view of the grants we received: 
starting with Stadt Münster & Sparkasse, followed by Make Light and now...

And mention the three awards by now:
- Make Light Challange (3rd place) 
- CItizen Science Zukunftsstadt
- ******* ***** *******

What is the best name for this tab in english and german?

**Comment by mpfeil** [comment]
We have a section for Awards and Grants. It´s placed in the footer under background.

- German => Auszeichnungen
- English => Awards

Right now nothing is on that page.

I don´t like the idea to create a new tab in the header. I would suggest to leave the link in the footer and:

1. create a new subsection on the background page or
2. a new own page but without a new entry in the header

**Comment by robarto** [comment]
The footer is too low and hidden for this rather important information...
I am also happy with the current menu (besides the missing news tab). 

1. The information about Grants (all fundings, schools/labs/people that received a sensebox) AND Awards would be too much for the background page.
2. A new page without entry in the menu could be the solution. as a link in the background section. but I beleive we will have to put the information in a more prominent position soon... "aus Gründen"

**Comment by robarto** [comment]
Can somebody prepare this site as in the uploaded doc?  
Link it to the Awards section in the footer first 
[Förderung.docx](https://github.com/sensebox/sensebox.github.io/files/158584/Forderung.docx)

**Comment by robarto** [comment]
@mpfeil 
Kannst du Dir das hier mal vornehmen? Ich hätte jetzt doch gerne einen eigenen Tab dazu oben, weil das einfach das beste marketing ist.
Der soll heißen Förderung&Preise bzw.  Grants&Awards   
englischer text kommt gleich

**Comment by robarto** [comment]
[senseBox_Awards.docx](https://github.com/sensebox/sensebox.github.io/files/208793/senseBox_Awards.docx)

**Comment by mpfeil** [comment]
![bildschirmfoto 2016-04-11 um 20 12 38](https://cloud.githubusercontent.com/assets/2471172/14437593/46912558-0022-11e6-96fd-ca30ae85465f.png)

@robarto: Ich möchte nochmal vorschlagen den Punkt nicht als Menüpunkt aufzuführen. Bei 1280x800 wird das Menü schon zweizeilig. 

Entweder passen wir die Schriftgröße an oder lassen es nur im Footer.
