### ISSUE TITLE
New Pics for products page

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#44]
should we change the pics on http://www.sensebox.de/de/products/
to these? 
[160211_senseBox_h_e_InhaltAufbau_TZ_beschriftzung.pdf](https://github.com/sensebox/sensebox.github.io/files/135230/160211_senseBox_h_e_InhaltAufbau_TZ_beschriftzung.pdf)

**Comment by chk1** [comment]
Those are too abstract in my opinion, you don't really know what you are looking at unless you visit the "buy now" link (one additional click...).

There should be 'real world' depictions of the components at least. There are no other detailed real world pictures of the senseBox and all of its components, except maybe under News and Documentation. 

For example:

![untitled sketch_steckplatine](https://cloud.githubusercontent.com/assets/828496/13152320/d9e59be6-d66e-11e5-8d08-2ee3b8429eac.png)

**Comment by Bernd90** [comment]
We should nonetheless change the pics. For the arduino::home there is a ultrasonic distance and a sensor and a display on the picture which is, as far as i know, not included in the box.
