### ISSUE TITLE
Press section, what to add?

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#46]
Should we list also mentions in blogs and on websites in the press section? there is this old one:

http://paderta.com/die-eigene-online-wetterstation-mit-arduino/

and very recent ones:
http://www.dortmund.de/de/leben_in_dortmund/nachrichtenportal/alle_nachrichten/nachricht.jsp?nid=400707
http://www.dortmund.de/de/leben_in_dortmund/bildungwissenschaft/start_bw/
http://www.vcd-dortmund.de/cms/front_content.php?idcat=120&idart=770&lang=1
https://jrf.nrw/2016/02/ils-sensebox/

**Comment by mpfeil** [comment]
:+1:

**Comment by FelixErdmann** [comment]
just added:
* http://paderta.com/die-eigene-online-wetterstation-mit-arduino/
* http://www.dortmund.de/de/leben_in_dortmund/nachrichtenportal/alle_nachrichten/nachricht.jsp?nid=400707
* https://jrf.nrw/2016/02/ils-sensebox/

found no articles in:
* http://www.dortmund.de/de/leben_in_dortmund/bildungwissenschaft/start_bw/
* http://www.vcd-dortmund.de/cms/front_content.php?idcat=120&idart=770&lang=1
