### ISSUE TITLE
broken URLs

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#47]
Dort wiederum bin ich auf http://www.sensebox.de/de/products/ auf den Kink zu den Anleitungen gestoßen, der auf http://www.sensebox.de/de/docd statt auf http://www.sensebox.de/de/docs verweist.

Dann wollte ich Ihnen das schreiben, und habe auf "Kontakt" geklickt. Der Link http://www.sensebox.de/de/products/de/contact/ ist auch kaputt.

**Comment by mpfeil** [comment]
fixed in 702ac52e21911d010f45e8c863e510839328b49a and cd4dbcec0ad6466d90da671724ea1c41aff317f9
