### ISSUE TITLE
Hackathon page

### ISSUE THREAD

**Issue by bgunt** [sensebox/sensebox.github.io#50]
Bitte unter Preise aus "senseBox:edu" die Mehrzahl machen und hinter dem "HIER BEWERBEN" das "Link zum Formular" durch "Die Bewerbungsphase startet bald!" ersetzen.

**Comment by robarto** [comment]
and more:

Womit wird gearbeitet? 
Wir stellen euch unser gesamtes Inventar zur Verfügung:
- senseBox:edu Sets 
- verschiede Arduinos
- eine Unzahl von Sensoren 
- Raspberry Pi
- verschiedene 3D-Drucker
- Microsoft Kinects
- Kameras
- Wetterballon
- Laptops, Tablets, Smartphones...

Es fehlen noch bildchen und ein kurzer Text zum CodeWeekAward mit dem Logo, ganz oben drüber.

**Comment by mpfeil** [comment]
@bgunt @robarto könnt ihr das CodeWeekAward Logo und Text zuschicken
