### ISSUE TITLE
code week award logo

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#51]
can you put the code week award logo to the top right? below language? 
and add the URL to the hackathon site

[CWA Gewinnerprojekt-Badge 2016 heller Hintergrund.svg.zip](https://github.com/sensebox/sensebox.github.io/files/179984/CWA.Gewinnerprojekt-Badge.2016.heller.Hintergrund.svg.zip)

**Comment by mpfeil** [comment]
on the frontpage? you mean as a "Störer" :stuck_out_tongue:

**Comment by robarto** [comment]
Yes, a Störer
Am 18.03.2016 20:47 schrieb "Matthias Pfeil" <notifications@github.com>:

**Comment by mpfeil** [comment]
What do you think?
![bildschirmfoto 2016-03-18 um 22 11 37](https://cloud.githubusercontent.com/assets/2471172/13892259/73824f8a-ed56-11e5-8f0f-25230f1a99dd.png)

**Comment by mpfeil** [comment]
or
![bildschirmfoto 2016-03-18 um 22 28 04](https://cloud.githubusercontent.com/assets/2471172/13892590/b8d4d4fc-ed58-11e5-8caa-0d4134720334.png)

**Comment by robarto** [comment]
Misunderstanding.
Just tho Störer on the right.
Leave the code week text on the hackathon side.
Put the first sentence of front page (sensebox is...) to the top. Störer
right.
Check how it looks...
Am 18.03.2016 22:12 schrieb "Matthias Pfeil" <notifications@github.com>:

**Comment by mpfeil** [comment]
something like this ????
![bildschirmfoto 2016-03-18 um 22 49 52](https://cloud.githubusercontent.com/assets/2471172/13893056/cb787854-ed5b-11e5-9439-e12b83b3b5ef.png)

**Comment by robarto** [comment]
Erst mal super denke ich...
Die Frage bleibt ob die super Designer vom Code week award ernsthaft times
für die bikdunterschrift nutzen wollten...
Am 18.03.2016 22:50 schrieb "Matthias Pfeil" <notifications@github.com>:

**Comment by mpfeil** [comment]
fragst du da nochmal nach?
soll es so online erstmal?

**Comment by robarto** [comment]
Mach erstmal on
Am 18.03.2016 22:57 schrieb "Matthias Pfeil" <notifications@github.com>:
