### ISSUE TITLE
new Press Line

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#60]
similar to the supporters line with grey logos we should have a "PRESS" line on the main page showing out major appearances in the media:

WDR, RBB, Deutschlandradio, ct, Make, smart magazine, RP, Aktion Mensch, Intel

Similar to this one: https://plumelabs.com/  (scroll down)

**Comment by FelixErdmann** [comment]
Sponsoren / Presse (Sponsors / Press)

or

Unterstützer / Presse (Supporters / Press)

?

![bildschirmfoto 2016-04-25 um 15 27 29](https://cloud.githubusercontent.com/assets/12086004/14785287/4b73604e-0afa-11e6-9c0e-b599568f9e63.png)
