### ISSUE TITLE
add Jury section to hackathon page 

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#61]
can we reuse the semi-automatic Team section here? so I can write the jury texts and fotos by myself...

**Comment by mpfeil** [comment]
I would suggest to add a new `jury.yml` file under `_data/members/de` and use the structure of [members.yml](https://github.com/sensebox/sensebox.github.io/blob/master/_data/team/de/members.yml)

@FelixErdmann could you create that file (or in a different folder) when you are working on #62

**Comment by FelixErdmann** [comment]
@robarto do you have any jury texts and fotos?

**Comment by robarto** [comment]
Hi Felix, kannst du die Texte ergänzen:


Grischa (noch in 3.Person um schreiben):
I am passionate about helping individuals from education, research and public sector develop digital strategies and make the best business aligned technology decisions.

Over the past 8+ years I built up and led teams, managed large accounts, implemented and grew customer centered programs and provided software, saas, volume licenses, training, support and consulting services to hundreds of organizations and thousands of users.

My expertise includes sales management, business development, marketing strategy, team leadership, key account management and driving growth within a defined vertical.

I earned a Diploma in Geography and GIS from University of Münster, attended leadership, IT & business courses and participated in a variety of international technology and research events.


Gerrit:
Gerrit Grunwald is a software engineer with more than ten years of experience in software development. He has been involved in Java desktop application and controls development. Gerrit is interested in Java on desktop, Java-driven embedded technologies based on JavaSE embedded and IoT in general. He is a true believer in open source and has participated in popular projects like JFXtras.org as well as his own projects (Medusa, Enzo, SteelSeries Swing, SteelSeries Canvas). 
Gerrit blogs regularly on subjects related to the Internet of Things and Java(FX) related topics, he is an active member of the Java community, where he founded and leads the Java User Group Münster (Germany), is a JavaOne rockstar and Java Champion. He is a speaker at conferences and user groups internationally and writes for several magazines.

Chris: hiersut: http://www.christian-kray.de/


Kannst du dann für alle ggf noch so Twitter / LinkedIn / Webseiten Symbole direkt hinter/unter den Namen hinzufügen und mit den Profilen verlinken?

Grüße,
Thomas

**Comment by FelixErdmann** [comment]
closed in 4ad4086

**Comment by mpfeil** [comment]
Können wir die Jury section noch etwas cooler gestalten?
Vorschlag (ist zu finden unter [Bootstrap Themes](http://themes.getbootstrap.com/) ):
![jury](https://cloud.githubusercontent.com/assets/2471172/15147430/f1bad00a-16c0-11e6-8e35-4ffb611b8cca.PNG)

Das Ganze ist gemacht mit [Bootstrap Panels](http://getbootstrap.com/components/#panels)

**Comment by robarto** [comment]
Sehr cool... Bin ich für! Ggf kommt noch jmd von Samsung dazu !

Am Dienstag, 10. Mai 2016 schrieb Matthias Pfeil :

> Können wir die Jury section noch etwas cooler gestalten?
> Vorschlag (ist zu finden unter Bootstrap Themes
> <http://themes.getbootstrap.com/> ):
> [image: jury]
> <https://cloud.githubusercontent.com/assets/2471172/15147430/f1bad00a-16c0-11e6-8e35-4ffb611b8cca.PNG>
>
> Das Ganze ist gemacht mit Bootstrap Panels
> <http://getbootstrap.com/components/#panels>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sensebox/sensebox.github.io/issues/61#issuecomment-218151852>
>


-- 
--

Thomas Bartoschek
ifgi - Institute for Geoinformatics
University of Münster
Heisenbergstr. 2
48149 Münster, Germany

Phone:  +49 (0)251 83 30011
Mobile: +49 (0)173 511 6094
Fax:    +49 (0)251 83 39763

Email: bartoschek@uni-muenster.de
http://ifgi.uni-muenster.de/
http://www.gi-at-school.de/
http://vespucci.org/

**Comment by FelixErdmann** [comment]
![](https://youtheman77.files.wordpress.com/2014/11/im-working-on-it.jpg)

**Comment by robarto** [comment]
sieht geil aus! 

hier noch Ergänzungen: 
https://www.linkedin.com/in/chris-kray-2bb2278
https://twitter.com/GadeShot

Grischa im Text mit c.

**Comment by FelixErdmann** [comment]
see 4f69bc801c53f18a04c66d9c604f1ce049ebedc3
