### ISSUE TITLE
last changes to hackathon page

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#63]
0. 
den Gewinner Badge auch nochmal irgendwo platzieren. rechts?

0. 
können die enumerations etwas größer sein?
in der ersten enumeration das Garmin weg. Nur smart watches.

1.
Eine neue seite anlegen und dort unser Anmeldeformular einbetten:
<script type="text/javascript" src="https://form.jotformeu.com/jsform/60682178338362"></script> 

2.
Aus den drei EinverständnisLinks den letzten löschen. Aus dem zweiten bitte die zahlen löschen. Die beiden hier verlinken:
[Einverständniserklärung_senseBox_Hackathon.pdf](https://github.com/sensebox/sensebox.github.io/files/259637/Einverstandniserklarung_senseBox_Hackathon.pdf)
[Einverständniserklärung U16_18.pdf](https://github.com/sensebox/sensebox.github.io/files/259638/Einverstandniserklarung.U16_18.pdf)

3.
Direkt darunter den link zum Bewerbungsformular. Zentriert und etwas auffälliger. 

4.
Darunter das mit der Unterkunft. Das Foto kann etwas kleiner und in ähnlichen Stil wie die Fotos oben. 

5. 
Können wir die Preise auch cooler darstellen? Also mit kachelartigen Fotos wie ganz oben? drei, wie sie dort gelistet sind (gerne mit URL dahinter zum jew. Produkt) und die letzte Kachel so "und mehr..." 

6.
Bei den Sponsoren gerne auch nochmal das CodeWeek + Samsung Logo von ganz oben bringen.

Dann haben wir es udn können die Ankündigung raushauen!!!!!

**Comment by robarto** [comment]
Hi Felix,
super geworden!!! DANKE!

**Comment by robarto** [comment]
Noch ne Frage:
ich kann bei dem Form-service einen CSS file hinzufügen, um das Formular in unseren Stil zu bringen. Wo ist ne CSS? das ding im CSS ordner funktioniert nicht. @mpfeil: kannst du ggf helfen?

**Comment by robarto** [comment]
@FelixErdmann kannst du bei den preisen noch die caption für den drucker und die watches kürzen, damit das alles eine höhe hat? also "3D-Drucker" und "Smartwachtes" z.B.

**Comment by FelixErdmann** [comment]
@robarto kommt immer auf die displaygröße an, bei mir auf dem laptop ist z.B. "senseBox:edu Sets" zweizeilig.. aber so sieht es im allgemeinen besser aus. 
Im _sass Ordner gibts die sensebox.scss Datei, da sind viele styles von uns drin
