### ISSUE TITLE
Add new links to gitbooks

### ISSUE THREAD

**Issue by mpfeil** [sensebox/sensebox.github.io#66]
Add new links to senseBox Books under docs:
- [x] http://www.sensebox.de/books/edu/de/index.html
- [x] http://www.sensebox.de/books/edu/en/index.html
- [x] http://www.sensebox.de/books/home/de/index.html
- [x] http://www.sensebox.de/books/home/en/index.html

**Comment by mpfeil** [comment]
Can we rearrange the buttons to a row with 3 columns and add the card design from the hackathon page with a short introduction for the books

**Comment by FelixErdmann** [comment]
620d4fc6e6a7fc36c8e80749752ad691427a9d2a
