### ISSUE TITLE
Add Licence to gitBooks

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#69]
Diese Materialien stehen als Open Educational Ressources (OER) unter der Lizenz... zur Verfügung. oder so...

Add licence info (on EACH page in footer?)  
https://creativecommons.org/licenses/by-sa/4.0/
Use  https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/CC-BY-SA_icon.svg/100px-CC-BY-SA_icon.svg.png   or bigger

**Comment by robarto** [comment]
Außerdem fehlen komplett die Credentials, also With (heart) vom senseBox Team, GI@School, ifgi, WWU Münster...

**Comment by mpfeil** [comment]
@mariopesch schau mal ob da was bei ist https://plugins.gitbook.com/browse?q=footer
