### ISSUE TITLE
Add language 

### ISSUE THREAD

**Issue by mpfeil** [sensebox/sensebox.github.io#7]
- [x] English

**Comment by mpfeil** [comment]
http://jekyll-langs.liaohuqiu.net/

**Comment by robarto** [comment]
think about a solution, smilar to learnosm.org where we can ask the crowd for translations

**Comment by mpfeil** [comment]
@robarto habe nun die seiten vorbereitet für die übersetzungen. haben wir für die aktuelle version übersetzungen? dann pflege ich die ein. falls nicht, würde ich die Version commiten und ihr müsst die sachen anpassen.

**Comment by robarto** [comment]
alles klar, ich verfeinere die alte Übesetzung, weil wir ja kleinigkeiten
an der Webseite geändert haben.
Soll ich Dir ein Doc schicken, oder wie kann ich so ein Language file
anlegen? Das würde ich gerne wissen, weil ich dann versuche noch ein paar
Sprachen klarzumachen ;)


2015-11-29 16:48 GMT+01:00 Matthias Pfeil <notifications@github.com>:

> @robarto <https://github.com/robarto> habe nun die seiten vorbereitet für
> die übersetzungen. haben wir für die aktuelle version übersetzungen? dann
> pflege ich die ein. falls nicht, würde ich die Version commiten und ihr
> müsst die sachen anpassen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sensebox/sensebox.github.io/issues/7#issuecomment-160423680>
> .
>



-- 
--

Thomas Bartoschek
ifgi - Institute for Geoinformatics
University of Münster
Heisenbergstr. 2
48149 Münster, Germany

Phone:  +49 (0)251 83 30011
Mobile: +49 (0)173 511 6094
Fax:    +49 (0)251 83 39763

Email: bartoschek@uni-muenster.de
http://ifgi.uni-muenster.de/
http://www.gi-at-school.de/
http://vespucci.org/

**Comment by mpfeil** [comment]
ja schick mir das einmal als doc zu dann legen ich das an und dann habt ihr direkt ein beispiel für sprachen.

**Comment by robarto** [comment]
hier alle Texte bis auf TEAM.
Kannst du die ruhig schon setzen, und ich bitte alle heute noch Team-Texte
zu schreiben.
Grüße,
Thomas

2015-11-30 9:50 GMT+01:00 Matthias Pfeil <notifications@github.com>:

> ja schick mir das einmal als doc zu dann legen ich das an und dann habt
> ihr direkt ein beispiel für sprachen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sensebox/sensebox.github.io/issues/7#issuecomment-160559309>
> .
>



-- 
--

Thomas Bartoschek
ifgi - Institute for Geoinformatics
University of Münster
Heisenbergstr. 2
48149 Münster, Germany

Phone:  +49 (0)251 83 30011
Mobile: +49 (0)173 511 6094
Fax:    +49 (0)251 83 39763

Email: bartoschek@uni-muenster.de
http://ifgi.uni-muenster.de/
http://www.gi-at-school.de/
http://vespucci.org/

**Comment by chk1** [comment]
@mpfeil Wie funktioniert das mit den Sprachen jetzt? Hast du das noch bei dir lokal, in einem Fork oder so? Will dir da keinen keinen merge conflict reinbringen, wenn ich was editiere

**Comment by robarto** [comment]
huch ;)

**Comment by robarto** [comment]
wenn man von einer unterseite, z.B. www.sensebox.de/de/products auf EN klickt, gehts zu www.sensebox.de/en

zurück auf DE, gehts zu 404, denn www.sensebox.de/de funtioniert nicht.

**Comment by mpfeil** [comment]
schau ich mir heute abend an, was da schief läuft.

**Comment by robarto** [comment]
alles klar. startseite, osem und docs sind fertig. der Rest in der Mittagspause ;)

**Comment by mpfeil** [comment]
:+1: sieht gut aus

**Comment by robarto** [comment]
19 days ago... ich habs kommentiert, due sagtest "schau ich mir heute abend an, was da schief läuft."
