### ISSUE TITLE
hackathon website changes

### ISSUE THREAD

**Issue by robarto** [sensebox/sensebox.github.io#70]
Nach "Verpflegung wird gestellt": "Fahrtkosten mit dem ÖPNV (regional) können übernommen werden."

---

Bei Womit wird gearbeitet?
"Amazon Echo" hinzufügen: http://www.faz.net/aktuell/wirtschaft/fruehaufsteher/lautsprecher-amazon-echo-hoert-als-assistent-auf-alexa-14177460.html

Die Liste ersetzen durch die kacheln wie bei den Sponsoren!?

---

Text über Grischa anpassen:
Grischa Gundelsweiler is the main contact within AWS for education, EdTech and research organizations in DACH.
He advises educators, researchers, IT staff and CxO’s on cloud, digital technologies and strategies. Furthermore AWS supports the next generation of IT and cloud professionals through multiple programs.
 
Grischa Gundelsweiler leitet den Bereich Bildung und Forschung für AWS in DACH und ist Ansprechpartner für Bildungseinrichtungen, EdTech Unternehmen, Bildungs- und Wissenschaftsverlage und Forschungseinrichtungen. Er berät Lehrer, Dozenten, Forscher, IT-Verantwortliche und die Leitungsebene zu digitalen Technologien und Strategien. Mit diversen Programmen unterstützt AWS zudem die nächste Generation an IT und Cloud Experten.

---

Bitte Amazon Web Services unter Sponsoren aufführen mit diesem Logo:
[poweredbyawslogos.zip](https://github.com/sensebox/sensebox.github.io/files/303074/poweredbyawslogos.zip)

---

Neuer Menüpunkt in diesem hackathon menü "Kontakt".
Text ganz unten:
Du hast noch Fragen? Schreib uns eine Mail (info@sensebox.de), kontaktiere uns bei Facebook Twitter (links) oder ruf uns an: +49 251 83 33083

**Comment by FelixErdmann** [comment]
5d9d1a30fe714488deaa4f3a0bbc5e57eb912209
