### ISSUE TITLE
Opt-Out cookies

### ISSUE THREAD

**Issue by mpfeil** [sensebox/sensebox.github.io#75]
@felixerdy  ich habe gerade den Piwik code auf den Piwik Server der Uni umgezogen.
Ich habe noch folgenden Hinweis aus dem ZIV erhalten:

> Bitte beachten sie, dass sie wenn sie Piwik-Tracking-Code auf Ihren Webseiten einfügen, von diesen Webseiten Cookies verwendet und beim User gesetzt werden. Sie sind damit dazu verpflichtet den Nutzer darüber aufzuklären und ihn ggf. ein Opt-Out anzubieten. Beispiele hierfür finden sie z. B. im globalen Impressum der WWU (http://www.uni-muenster.de/de/impressum.html).

Kannst du dich darum kümmern bitte

**Comment by felixerdy** [comment]
closed in 45a59125eaad3d3478b3faed10d5aaa94042007f and f188332bb4582abe08876f6d38f92e52e1b7f57e
