### ISSUE TITLE
Bildergalerie für Blogposts

### ISSUE THREAD

**Issue by benzmanu** [sensebox/sensebox.github.io#97]
Für mehrere Bilder wäre es super, wenn in dem Blogbeitrag eine Bildergalerie möglich wäre, z.B. wenns ein Beitrag von der Cebit mit vielen Bildern gibt
Bzw. es wäre cool überhaupt Bilder in dem Blogbeitrag einfügen zu können und nicht nur auf der Übersichtsseite

**Comment by robarto** [comment]
Sehe ich auch so!

**Comment by mpfeil** [comment]
@benzmanu kannst du einmal in Issue #113 schauen, ob dir das mit den Bilder so genügt oder ob du noch eine echte Galerie für Bilder benötigst?

**Comment by benzmanu** [comment]
ich denke, dass das erstmal so reicht. Vielleicht ergibt es sich mal bei irgendeinem Blogbeitrag, dass eine Bildergalerie ganz geschickt wäre. Aber so ists auf jeden Fall erstmal gut. Danke!
